name: CI
on: push
jobs:
  CI:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Python
        uses: actions/checkout@v3

      - name: Install Python
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"

      - name: Install Poetry
        uses: snok/install-poetry@v1.3.1
        with:
          virtualenvs-in-project: true

      - name: Cache Dependencies
        uses: actions/cache@v2
        id: cache
        with:
          path: .venv
          key: venv-${{ runner.os }}-${{ steps.setup-python.outputs.python-version }}-${{ hashFiles('**/poetry.lock') }}

      - name: Install Dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: poetry install

      - name: Code Formatting
        run: black . --check

      - name: Sorted Imports
        run: isort thoth --check --diff

      - name: Code Quality
        run: pylint thoth

      - name: Check Type Hints
        run: mypy thoth